# This is a Docker Compose file for a VPN and an application.

version: "3.8"  # Specifies the version of Docker Compose to use.

services:  # Defines the services (containers) that make up the application.

  # The VPN service uses the qmcgaw/gluetun image and is named "gluetun".
  # It has NET_ADMIN capabilities and uses the /dev/net/tun device.
  # It also has various environment variables for configuring the VPN.
  # The VPN listens on ports 80 and 8080 and restarts if it fails.
  vpn:
    image: qmcgaw/gluetun:v3.34
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=
      - VPN_TYPE=
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - WIREGUARD_PRIVATE_KEY=
      - WIREGUARD_ADDRESS=
      - WIREGUARD_PUBLIC_KEY=
      - TZ=Asia/Kolkata
      - UPDATER_PERIOD=24h
    ports:
      - "80:80"
      - "8080:808
