version: "3.8"
services:
  vpn:
    image: qmcgaw/gluetun:v3.34
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=
      - VPN_TYPE=
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - TZ=Asia/Kolkata
      - UPDATER_PERIOD=24h
    volumes:
      - ./gluetun-config:/app/gluetun-config
    ports:
      - "80:80"
      - "8080:8080"
    restart: on-failure

  app:
    build: .
    network_mode: service:vpn
    command: bash start.sh
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"
